# Generated by Django 5.1.6 on 2025-02-24 19:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('communityApp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='community',
            name='bannerImage_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='community',
            name='profileImage_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='community',
            name='rules',
            field=models.TextField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='community',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
