# Generated by Django 5.1.6 on 2025-02-24 19:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('communityApp', '0002_community_bannerimage_url_community_profileimage_url_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='community',
            old_name='CommunityBasedOn',
            new_name='communityBasedOn',
        ),
        migrations.RenameField(
            model_name='community',
            old_name='profileImage_url',
            new_name='communityImage_url',
        ),
    ]
