# Generated by Django 5.1.6 on 2025-02-24 19:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('communityApp', '0003_rename_communitybasedon_community_communitybasedon_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='community',
            old_name='communityBasedOn',
            new_name='community_based_on',
        ),
    ]
