# Generated by Django 5.1.6 on 2025-02-25 04:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('communityApp', '0004_rename_communitybasedon_community_community_based_on'),
    ]

    operations = [
        migrations.RenameField(
            model_name='community',
            old_name='created_by',
            new_name='owner',
        ),
    ]
