# Generated by Django 5.1.6 on 2025-02-25 08:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('communityApp', '0005_rename_created_by_community_owner'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='community',
            name='members',
        ),
        migrations.AddField(
            model_name='community',
            name='total_members',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
