# Generated by Django 5.1.6 on 2025-02-25 09:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('communityApp', '0007_remove_community_total_members'),
    ]

    operations = [
        migrations.AddField(
            model_name='community',
            name='members',
            field=models.ManyToManyField(blank=True, related_name='communities_joined', to='communityApp.profile'),
        ),
    ]
